# -*- coding: utf-8 -*-
"""Task_04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wjDfdknGhVPnTc0wpeA5xFwND6bwY6Ru
"""

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Dataset/Twitter Sentiment/Brand Sentiment/twitter_training.csv",
                 header=None,
                 names=["tweet_id", "topic", "sentiment", "text"])

df.info()

df.head()

df["sentiment"].unique()

import matplotlib.pyplot as plt
import seaborn as sns

df = df.dropna(subset=["sentiment", "topic"])
df["sentiment"] = df["sentiment"].str.lower()

plt.figure()
sns.countplot(data=df, x="sentiment")
plt.title("Overall Sentiment Distribution")
plt.show()

top_topic = df["topic"].value_counts().head(10)

plt.figure()
top_topic.plot(kind="bar")
plt.title("Top 10 Most Mentioned Topics")
plt.ylabel("Tweet Count")
plt.show()

sentiment_topic = (
    df.groupby(["topic", "sentiment"])
    .size()
    .reset_index(name="count")
)

top10 = top_topic.index
sentiment_topic = sentiment_topic[sentiment_topic["topic"].isin(top10)]

# plot
plt.figure(figsize=(10,6))
sns.barplot(
    data=sentiment_topic,
    x="topic",
    y="count",
    hue="sentiment"
)

plt.xticks(rotation=45)
plt.title("Sentiment Distribution per Top Topic")
plt.show()

import numpy as np

negative_ratio = (
    df.assign(is_negative=df["sentiment"] == "negative")
    .groupby("topic")["is_negative"]
    .mean()
    .sort_values(ascending=False)
    .head(10)
)

values = negative_ratio.values
labels = negative_ratio.index
y_pos = np.arange(len(values))

fig, ax = plt.subplots(figsize=(10,5))
ax.barh(
    y_pos,
    [1] * len(values),
    color="#e0e0e0",
    height=0.6
)

ax.barh(
    y_pos,
    values,
    color=plt.cm.Reds(values / values.max()),
    height=0.6
)

ax.set_yticks(y_pos)
ax.set_yticklabels(labels)
ax.invert_yaxis()
ax.set_xlim(0, 1)
ax.set_title("Top 10 Brands with Highest Negative Sentiment Ratio")
ax.set_xlabel("Negative Sentiment Ratio")

for i, v in enumerate(values):
  ax.text(
      v - 0.03 if v > 0.08 else v + 0.02,
      i,
      f"{v:.0%}",
      va="center",
      ha="right" if v > 0.08 else "left",
      color="white" if v > 0.08 else "black",
      fontsize=9,
      fontweight="bold"
  )

ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.spines["left"].set_visible(False)
ax.tick_params(axis="y", length=0)

plt.tight_layout()
plt.show()

