# -*- coding: utf-8 -*-
"""Task_04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wjDfdknGhVPnTc0wpeA5xFwND6bwY6Ru
"""

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Dataset/Twitter Sentiment/Brand Sentiment/twitter_training.csv",
                 header=None,
                 names=["tweet_id", "topic", "sentiment", "text"])

df.info()

df.head()

df["sentiment"].unique()

import matplotlib.pyplot as plt
import seaborn as sns

df = df.dropna(subset=["sentiment", "topic"])
df["sentiment"] = df["sentiment"].str.lower()

plt.figure()
sns.countplot(data=df, x="sentiment")
plt.title("Overall Sentiment Distribution")
plt.show()

top_topic = df["topic"].value_counts().head(10)

plt.figure()
top_topic.plot(kind="bar")
plt.title("Top 10 Most Mentioned Topics")
plt.ylabel("Tweet Count")
plt.show()

sentiment_topic = (
    df.groupby(["topic", "sentiment"])
    .size()
    .reset_index(name="count")
)

top10 = top_topic.index
sentiment_topic = sentiment_topic[sentiment_topic["topic"].isin(top10)]

# plot
plt.figure(figsize=(10,6))
sns.barplot(
    data=sentiment_topic,
    x="topic",
    y="count",
    hue="sentiment"
)

plt.xticks(rotation=45)
plt.title("Sentiment Distribution per Top Topic")
plt.show()

negative_ratio = (
    df.assign(is_negative=df["sentiment"] == "negative")
    .groupby("topic")["is_negative"]
    .mean()
    .sort_values(ascending=False)
    .head(10)
)

plt.figure()
negative_ratio.plot(kind="bar")
plt.title("Top 10 Brands with Highest Negative Sentiment Ratio")
plt.ylabel("Negative Sentiment Ratio")
plt.show()

